import medspacy
from medspacy.ner import TargetRule
from medspacy.visualization import visualize_ent

def load_nlp():
    # load medspacy model
    nlp = medspacy.load()

    # loading rules for target concept extraction
    target_matcher = nlp.get_pipe("medspacy_target_matcher")
    
    target_rules = [
        # Heart Disease
        TargetRule("coronary artery disease", "HEART_DISEASE"),
        TargetRule("myocardial infarction", "HEART_DISEASE"),
        TargetRule("heart failure", "HEART_DISEASE"),
        TargetRule("arrhythmia", "HEART_DISEASE"),
        TargetRule("atrial fibrillation", "HEART_DISEASE"),
        TargetRule("cardiomyopathy", "HEART_DISEASE"),
        TargetRule("congenital heart disease", "HEART_DISEASE"),
        TargetRule("aortic stenosis", "HEART_DISEASE"),
        TargetRule("aortic valve stenosis", "HEART_DISEASE"),
        TargetRule("pericarditis", "HEART_DISEASE"),
        TargetRule("endocarditis", "HEART_DISEASE"),
        TargetRule("statin", "HEART_DISEASE_MEDICATION"),
        TargetRule("beta-blocker", "HEART_DISEASE_MEDICATION"),
        TargetRule("diuretic", "HEART_DISEASE_MEDICATION"),
        TargetRule("ACE inhibitor", "HEART_DISEASE_MEDICATION"),
        TargetRule("angiotensin II receptor blocker", "HEART_DISEASE_MEDICATION"),
        TargetRule("calcium channel blocker", "HEART_DISEASE_MEDICATION"),
        TargetRule("anticoagulant", "HEART_DISEASE_MEDICATION"),
        TargetRule("antiplatelet agent", "HEART_DISEASE_MEDICATION"),
        TargetRule("nitrate", "HEART_DISEASE_MEDICATION"),
        TargetRule("digoxin", "HEART_DISEASE_MEDICATION"),
        TargetRule("beta adrenergic blocker", "HEART_DISEASE_MEDICATION"),
        TargetRule("renin-angiotensin system inhibitor", "HEART_DISEASE_MEDICATION"),
        TargetRule("calcium channel blocker", "HEART_DISEASE_MEDICATION"),
        TargetRule("diuretic", "HEART_DISEASE_MEDICATION"),
        TargetRule("antiarrhythmic medication", "HEART_DISEASE_MEDICATION"),
        TargetRule("vasodilator", "HEART_DISEASE_MEDICATION"),
        TargetRule("antiplatelet therapy", "HEART_DISEASE_MEDICATION"),
        TargetRule("nitrates", "HEART_DISEASE_MEDICATION"),
        TargetRule("aldosterone antagonist", "HEART_DISEASE_MEDICATION"),
        TargetRule("digoxin", "HEART_DISEASE_MEDICATION"),
        TargetRule("angiotensin-converting enzyme inhibitor", "HEART_DISEASE_MEDICATION"),
        TargetRule("atrial septal defect", "HEART_DISEASE"),
        TargetRule("ventricular septal defect", "HEART_DISEASE"),
        TargetRule("patent ductus arteriosus", "HEART_DISEASE"),
        TargetRule("ventricular septal rupture", "HEART_DISEASE"),

        TargetRule("coronary angiography", "HEART_DISEASE_PROCEDURE"),
        TargetRule("cardiac catheterization", "HEART_DISEASE_PROCEDURE"),
        TargetRule("angioplasty with stent placement", "HEART_DISEASE_PROCEDURE"),
        TargetRule("coronary artery bypass grafting", "HEART_DISEASE_PROCEDURE"),
        TargetRule("valve repair", "HEART_DISEASE_PROCEDURE"),
        TargetRule("valve replacement", "HEART_DISEASE_PROCEDURE"),
        TargetRule("heart transplantation", "HEART_DISEASE_PROCEDURE"),
        TargetRule("implantation of pacemaker", "HEART_DISEASE_PROCEDURE"),
        TargetRule("implantation of defibrillator", "HEART_DISEASE_PROCEDURE"),
        TargetRule("cardiac rehabilitation", "HEART_DISEASE_PROCEDURE"),

        # Heart Disease Vitals
        TargetRule("blood pressure", "HEART_DISEASE_VITAL"),
        TargetRule("heart rate", "HEART_DISEASE_VITAL"),
        TargetRule("electrocardiogram result", "HEART_DISEASE_VITAL"),
        TargetRule("echocardiogram result", "HEART_DISEASE_VITAL"),
        TargetRule("exercise stress test outcome", "HEART_DISEASE_VITAL"),
        TargetRule("blood lipid level", "HEART_DISEASE_VITAL"),
        TargetRule("C-reactive protein level", "HEART_DISEASE_VITAL"),

        # Heart Disease Medications
        TargetRule("statin", "HEART_DISEASE_MEDICATION"),
        TargetRule("beta-blocker", "HEART_DISEASE_MEDICATION"),
        TargetRule("diuretic", "HEART_DISEASE_MEDICATION"),
        TargetRule("ACE inhibitor", "HEART_DISEASE_MEDICATION"),
        TargetRule("angiotensin II receptor blocker", "HEART_DISEASE_MEDICATION"),
        TargetRule("calcium channel blocker", "HEART_DISEASE_MEDICATION"),
        TargetRule("anticoagulant", "HEART_DISEASE_MEDICATION"),
        TargetRule("antiplatelet agent", "HEART_DISEASE_MEDICATION"),
        TargetRule("nitrate", "HEART_DISEASE_MEDICATION"),
        TargetRule("digoxin", "HEART_DISEASE_MEDICATION"),

        # Cancer
        TargetRule("malignant neoplasm", "CANCER"),
        TargetRule("breast cancer", "CANCER"),
        TargetRule("lung cancer", "CANCER"),
        TargetRule("colorectal cancer", "CANCER"),
        TargetRule("leukemia", "CANCER"),
        TargetRule("lymphoma", "CANCER"),
        TargetRule("metastasis", "CANCER"),
        TargetRule("sarcoma", "CANCER"),
        TargetRule("cervical cancer", "CANCER"),
        TargetRule("carcinoma", "CANCER"),
        TargetRule("carcinoma in situ", "CANCER"),
        TargetRule("paraneoplastic syndrome", "CANCER"),
        TargetRule("chemotherapy", "CANCER_TREATMENT"),
        TargetRule("radiotherapy", "CANCER_TREATMENT"),
        TargetRule("immunotherapy", "CANCER_TREATMENT"),
        TargetRule("targeted therapy", "CANCER_TREATMENT"),
        TargetRule("hormone therapy", "CANCER_TREATMENT"),
        TargetRule("stem cell transplant", "CANCER_TREATMENT"),
        TargetRule("checkpoint inhibitor", "CANCER_TREATMENT"),
        TargetRule("monoclonal antibody therapy", "CANCER_TREATMENT"),
        TargetRule("tyrosine kinase inhibitor", "CANCER_TREATMENT"),
        TargetRule("biologic therapy", "CANCER_TREATMENT"),
        TargetRule("cancer vaccine", "CANCER_TREATMENT"),
        TargetRule("targeted molecular therapy", "CANCER_TREATMENT"),
        TargetRule("radiosensitizer", "CANCER_TREATMENT"),
        TargetRule("immune checkpoint blockade", "CANCER_TREATMENT"),
        TargetRule("oncolytic virus therapy", "CANCER_TREATMENT"),
        TargetRule("proton therapy", "CANCER_TREATMENT"),
        TargetRule("cytokine therapy", "CANCER_TREATMENT"),
        TargetRule("neoadjuvant therapy", "CANCER_TREATMENT"),
        TargetRule("adjuvant therapy", "CANCER_TREATMENT"),
        TargetRule("targeted drug delivery", "CANCER_TREATMENT"),

        TargetRule("biops","CANCER_PROCEDURE"),
        TargetRule("mastectomy", "CANCER_PROCEDURE"),
        TargetRule("lumpectomy", "CANCER_PROCEDURE"),
        TargetRule("radiotherapy", "CANCER_PROCEDURE"),
        TargetRule("chemotherapy", "CANCER_PROCEDURE"),
        TargetRule("immunotherapy", "CANCER_PROCEDURE"),
        TargetRule("targeted therapy", "CANCER_PROCEDURE"),
        TargetRule("hormone therapy", "CANCER_PROCEDURE"),
        TargetRule("stem cell transplant", "CANCER_PROCEDURE"),
        # Cancer Vitals
        TargetRule("tumor marker", "CANCER_VITAL"),
        TargetRule("complete blood count", "CANCER_VITAL"),
        TargetRule("CT scan result", "CANCER_VITAL"),
        TargetRule("MRI scan result", "CANCER_VITAL"),
        TargetRule("PET scan result", "CANCER_VITAL"),
        TargetRule("biopsy result", "CANCER_VITAL"),    TargetRule("pain score", "CANCER_VITAL"),
        TargetRule("nutritional status", "CANCER_VITAL"),

        # Cancer Medications
        TargetRule("cytotoxic chemotherapy", "CANCER_MEDIC"),
        TargetRule("hormone therapy", "CANCER_MEDICATION"),
        TargetRule("targeted therapy", "CANCER_MEDICATION"),
        TargetRule("immunotherapy", "CANCER_MEDICATION"),
        TargetRule("bisphosphonate", "CANCER_MEDICATION"),

        # Chronic Lung Disease
        TargetRule("chronic obstructive pulmonary disease", "LUNG_DISEASE"),
        TargetRule("emphysema", "LUNG_DISEASE"),
        TargetRule("chronic bronchitis", "LUNG_DISEASE"),
        TargetRule("asthma", "LUNG_DISEASE"),
        TargetRule("pulmonary fibrosis", "LUNG_DISEASE"),
        TargetRule("cystic fibrosis", "LUNG_DISEASE"),
        TargetRule("occupational lung disease", "LUNG_DISEASE"),
        TargetRule("inhaled corticosteroid", "LUNG_DISEASE_MEDICATION"),
        TargetRule("long-acting beta agonist", "LUNG_DISEASE_MEDICATION"),
        TargetRule("long-acting muscarinic antagonist", "LUNG_DISEASE_MEDICATION"),
        TargetRule("methylxanthine", "LUNG_DISEASE_MEDICATION"),
        TargetRule("phosphodiesterase-4 inhibitor", "LUNG_DISEASE_MEDICATION"),
        TargetRule("mucolytic", "LUNG_DISEASE_MEDICATION"),
        TargetRule("bronchodilator", "LUNG_DISEASE_MEDICATION"),
        TargetRule("leukotriene modifier", "LUNG_DISEASE_MEDICATION"),
        TargetRule("anti-IgE therapy", "LUNG_DISEASE_MEDICATION"),
        TargetRule("pulmonary rehabilitation", "LUNG_DISEASE_TREATMENT"),
        TargetRule("lung volume reduction surgery", "LUNG_DISEASE_TREATMENT"),
        TargetRule("extracorporeal membrane oxygenation", "LUNG_DISEASE_TREATMENT"),
        TargetRule("tracheostomy", "LUNG_DISEASE_TREATMENT"),
        TargetRule("lung transplant", "LUNG_DISEASE_TREATMENT"),
        TargetRule("pulmonary artery hypertension", "LUNG_DISEASE"),
        TargetRule("bronchiectasis", "LUNG_DISEASE"),
        TargetRule("incentive spirometry", "LUNG_DISEASE_PROCEDURE"),        
        TargetRule("spirometry", "LUNG_DISEASE_PROCEDURE"),
        TargetRule("bronchoscopy", "LUNG_DISEASE_PROCEDURE"),
        TargetRule("lung volume reduction surgery", "LUNG_DISEASE_PROCEDURE"),
        TargetRule("lung transplantation", "LUNG_DISEASE_PROCEDURE"),
        TargetRule("pulmonary rehabilitation", "LUNG_DISEASE_PROCEDURE"),
        TargetRule("continuous positive airway pressure", "LUNG_DISEASE_PROCEDURE"),
        TargetRule("mechanical ventilation", "LUNG_DISEASE_PROCEDURE"),

        # Chronic Lung Disease Vitals
        TargetRule("oxygen saturation", "LUNG_DISEASE_VITAL"),
        TargetRule("pulmonary function test result", "LUNG_DISEASE_VITAL"),
        TargetRule("arterial blood gas analysis", "LUNG_DISEASE_VITAL"),
        TargetRule("body plethysmography", "LUNG_DISEASE_VITAL"),
        TargetRule("diffusing capacity of the lungs for carbon monoxide", "LUNG_DISEASE_VITAL"),
        TargetRule("6-minute walk test distance", "LUNG_DISEASE_VITAL"),

        # Chronic Lung Disease Medications
        TargetRule("inhaled corticosteroid", "LUNG_DISEASE_MEDICATION"),
        TargetRule("long-acting beta agonist", "LUNG_DISEASE_MEDICATION"),
        TargetRule("long-acting muscarinic antagonist", "LUNG_DISEASE_MEDICATION"),
        TargetRule("methylxanthine", "LUNG_DISEASE_MEDICATION"),
        TargetRule("phosphodiesterase-4 inhibitor", "LUNG_DISEASE_MEDICATION"),
        TargetRule("mucolytic", "LUNG_DISEASE_MEDICATION"),
        TargetRule("bronchodilator", "LUNG_DISEASE_MEDICATION"),
        TargetRule("antibiotic for exacerbation", "LUNG_DISEASE_MEDICATION"),

        # Stroke
        TargetRule("ischemic stroke", "STROKE"),
        TargetRule("hemorrhagic stroke", "STROKE"),
        TargetRule("transient ischemic attack", "STROKE"),
        TargetRule("subarachnoid hemorrhage", "STROKE"),
        TargetRule("cerebral aneurysm", "STROKE"),
        TargetRule("vascular malformation", "STROKE"),
        TargetRule("anticoagulant", "STROKE_MEDICATION"),
        TargetRule("antiplatelet", "STROKE_MEDICATION"),
        TargetRule("tissue plasminogen activator", "STROKE_MEDICATION"),
        TargetRule("statin", "STROKE_MEDICATION"),
        TargetRule("thrombolytic therapy", "STROKE_MEDICATION"),
        TargetRule("antiplatelet therapy", "STROKE_MEDICATION"),
        TargetRule("anticoagulant therapy", "STROKE_MEDICATION"),
        TargetRule("carotid endarterectomy", "STROKE_TREATMENT"),
        TargetRule("intravenous thrombolysis", "STROKE_TREATMENT"),
        TargetRule("mechanical thrombectomy", "STROKE_TREATMENT"),
        TargetRule("neuroprotective therapy", "STROKE_TREATMENT"),
        TargetRule("carotid artery stenting", "STROKE_TREATMENT"),
        TargetRule("intracranial stenting", "STROKE_TREATMENT"),
        TargetRule("thrombectomy", "STROKE_TREATMENT"),

        # Alzheimer's Disease
        TargetRule("mild cognitive impairment", "ALZHEIMERS"),
        TargetRule("dementia", "ALZHEIMERS"),
        TargetRule("Lewy body dementia", "ALZHEIMERS"),
        TargetRule("frontotemporal dementia", "ALZHEIMERS"),
        TargetRule("vascular dementia", "ALZHEIMERS"),
        TargetRule("mixed dementia", "ALZHEIMERS"),
        TargetRule("sundowning", "ALZHEIMERS"),
        TargetRule("cholinesterase inhibitor", "ALZHEIMERS_MEDICATION"),
        TargetRule("donepezil", "ALZHEIMERS_MEDICATION"),
        TargetRule("rivastigmine", "ALZHEIMERS_MEDICATION"),
        TargetRule("NMDA receptor antagonist", "ALZHEIMERS_MEDICATION"),
        TargetRule("memantine", "ALZHEIMERS_MEDICATION"),
        TargetRule("acetylcholinesterase inhibitor", "ALZHEIMERS_MEDICATION"),
        TargetRule("amyloid beta-targeting therapy", "ALZHEIMERS_MEDICATION"),
        TargetRule("tau protein inhibitor", "ALZHEIMERS_MEDICATION"),
        TargetRule("neuroprotective agent", "ALZHEIMERS_MEDICATION"),
        TargetRule("neuroregenerative therapy", "ALZHEIMERS_TREATMENT"),
        TargetRule("cognitive training", "ALZHEIMERS_TREATMENT"),
        TargetRule("behavioral therapy", "ALZHEIMERS_TREATMENT"),
        TargetRule("environmental modification", "ALZHEIMERS_TREATMENT"),
        TargetRule("music therapy", "ALZHEIMERS_TREATMENT"),
        TargetRule("cerebrospinal fluid analysis", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("positron emission tomography (PET)", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("magnetic resonance imaging (MRI)", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("computed tomography (CT)", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("amyloid imaging", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("tau imaging", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("neurofibrillary tangle imaging", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("brain atrophy", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("hippocampal volume", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("cortical thickness", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("white matter hyperintensities", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("neurodegeneration markers", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("amyloid plaques", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("neurofibrillary tangles", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("cerebral blood flow", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("cerebral metabolism", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("hippocampal atrophy", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("frontal lobe atrophy", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("temporal lobe atrophy", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("parietal lobe atrophy", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("occipital lobe atrophy", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("entorhinal cortex atrophy", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("amygdala atrophy", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("thalamus atrophy", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("basal ganglia atrophy", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("brainstem atrophy", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("cerebellar atrophy", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("medial temporal lobe atrophy", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("frontotemporal atrophy", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("temporoparietal atrophy", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("neurofibrillary tangle burden", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("amyloid burden", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("brain connectivity", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("default mode network", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("salience network", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("executive control network", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("memory network", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("visuospatial network", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("attention network", "ALZHEIMERS_FUNCTION_TEST"),
        TargetRule("language network", "ALZHEIMERS_FUNCTION_TEST"),

        TargetRule("cognitive assessment", "ALZHEIMERS_PROCEDURE"),
        TargetRule("neuropsychological testing", "ALZHEIMERS_PROCEDURE"),
        TargetRule("cerebrospinal fluid analysis", "ALZHEIMERS_PROCEDURE"),
        TargetRule("amyloid PET imaging", "ALZHEIMERS_PROCEDURE"),
        TargetRule("MRI of the brain", "ALZHEIMERS_PROCEDURE"),
        TargetRule("CT of the brain", "ALZHEIMERS_PROCEDURE"),
        TargetRule("occupational therapy", "ALZHEIMERS_PROCEDURE"),
        TargetRule("speech therapy", "ALZHEIMERS_PROCEDURE"),

        # Alzheimer's Disease Vitals
        TargetRule("Mini-Mental State Examination score", "ALZHEIMERS_VITAL"),
        TargetRule("Montreal Cognitive Assessment score", "ALZHEIMERS_VITAL"),
        TargetRule("activities of daily living assessment", "ALZHEIMERS_VITAL"),
        TargetRule("instrumental activities of daily living assessment", "ALZHEIMERS_VITAL"),

        # Alzheimer's Disease Medications
        TargetRule("cholinesterase inhibitor", "ALZHEIMERS_MEDICATION"),
        TargetRule("donepezil", "ALZHEIMERS_MEDICATION"),
        TargetRule("rivastigmine", "ALZHEIMERS_MEDICATION"),
        TargetRule("NMDA receptor antagonist", "ALZHEIMERS_MEDICATION"),
        TargetRule("memantine", "ALZHEIMERS_MEDICATION"),
        TargetRule("antidepressant for behavioral symptoms", "ALZHEIMERS_MEDICATION"),
        TargetRule("anxiolytic for behavioral symptoms", "ALZHEIMERS_MEDICATION"),
        TargetRule("antipsychotic for behavioral symptoms", "ALZHEIMERS_MEDICATION"),

        # Diabetes
        TargetRule("type 1 diabetes", "DIABETES"),
        TargetRule("type 2 diabetes", "DIABETES"),
        TargetRule("diabetes mellitus", "DIABETES"),
        TargetRule("gestational diabetes", "DIABETES"),
        TargetRule("diabetes mellitus type 2", "DIABETES"),
        TargetRule("diabetic neuropathy", "DIABETES_COMPLICATION"),
        TargetRule("diabetic retinopathy", "DIABETES_COMPLICATION"),
        TargetRule("diabetic nephropathy", "DIABETES_COMPLICATION"),
        TargetRule("diabetic foot ulcer", "DIABETES_COMPLICATION"),
        TargetRule("insulin", "DIABETES_MEDICATION"),
        TargetRule("metformin", "DIABETES_MEDICATION"),
        TargetRule("sulfonylurea", "DIABETES_MEDICATION"),
        TargetRule("meglitinide", "DIABETES_MEDICATION"),
        TargetRule("thiazolidinedione", "DIABETES_MEDICATION"),
        TargetRule("dipeptidyl peptidase-4 inhibitor", "DIABETES_MEDICATION"),
        TargetRule("glucagon-like peptide-1 receptor agonist", "DIABETES_MEDICATION"),
        TargetRule("sodium-glucose cotransporter 2 inhibitor", "DIABETES_MEDICATION"),
        TargetRule("insulin pump", "DIABETES_TREATMENT"),
        TargetRule("continuous glucose monitoring", "DIABETES_TREATMENT"),
        TargetRule("intensive insulin therapy", "DIABETES_TREATMENT"),
        TargetRule("islet cell transplantation", "DIABETES_TREATMENT"),
        TargetRule("diabetic ketoacidosis", "DIABETES_COMPLICATION"),
        TargetRule("hyperosmolar hyperglycemic state", "DIABETES_COMPLICATION"),
        TargetRule("hypoglycemia unawareness", "DIABETES_COMPLICATION"),
        TargetRule("diabetic foot infection", "DIABETES_COMPLICATION"),
        TargetRule("insulin dependent", "DIABETES_MEDICATION"),
        TargetRule("insulin-dependent", "DIABETES_MEDICATION"),
        TargetRule("insulin lispro", "DIABETES_MEDICATION"),
        TargetRule("insulin glargine", "DIABETES_MEDICATION"),
        TargetRule("insulin aspart", "DIABETES_MEDICATION"),
        TargetRule("insulin detemir", "DIABETES_MEDICATION"),
        TargetRule("insulin degludec", "DIABETES_MEDICATION"),
        TargetRule("insulin glulisine", "DIABETES_MEDICATION"),
        TargetRule("insulin human", "DIABETES_MEDICATION"),
        TargetRule("insulin analog", "DIABETES_MEDICATION"),
        TargetRule("insulin pump therapy", "DIABETES_TREATMENT"),
        TargetRule("continuous glucose monitoring", "DIABETES_TREATMENT"),
        TargetRule("intensive insulin management", "DIABETES_TREATMENT"),
        TargetRule("islet cell transplant", "DIABETES_TREATMENT"),
        TargetRule("diabetic ketoacidosis", "DIABETES_COMPLICATION"),
        TargetRule("hyperosmolar hyperglycemic state", "DIABETES_COMPLICATION"),
        TargetRule("hypoglycemia unawareness", "DIABETES_COMPLICATION"),
        TargetRule("diabetic foot infection", "DIABETES_COMPLICATION"),
        TargetRule("glycated hemoglobin (HbA1c)", "DIABETES_FUNCTION_TEST"),
        TargetRule("blood glucose monitoring", "DIABETES_FUNCTION_TEST"),
        TargetRule("insulin sensitivity test", "DIABETES_FUNCTION_TEST"),
        TargetRule("oral glucose tolerance test", "DIABETES_FUNCTION_TEST"),
        TargetRule("C-peptide test", "DIABETES_FUNCTION_TEST"),
        TargetRule("insulin antibody test", "DIABETES_FUNCTION_TEST"),
        TargetRule("urine microalbumin test", "DIABETES_FUNCTION_TEST"),
        TargetRule("kidney function test", "DIABETES_FUNCTION_TEST"),
        TargetRule("retinal examination", "DIABETES_FUNCTION_TEST"),
        TargetRule("foot examination", "DIABETES_FUNCTION_TEST"),
        TargetRule("renal artery", "DIABETES_ANATOMY"),
        TargetRule("pancreas", "DIABETES_ANATOMY"),
        TargetRule("islet cells", "DIABETES_ANATOMY"),
        TargetRule("insulin-producing cells", "DIABETES_ANATOMY"),
        TargetRule("urethra", "DIABETES_ANATOMY"),
        TargetRule("ureters", "DIABETES_ANATOMY"),
        TargetRule("nephrons", "DIABETES_ANATOMY"),
        TargetRule("renal cortex", "DIABETES_ANATOMY"),
        TargetRule("renal medulla", "DIABETES_ANATOMY"),
        TargetRule("renal pyramids", "DIABETES_ANATOMY"),
        TargetRule("renal pelvis", "DIABETES_ANATOMY"),
        TargetRule("glomeruli", "DIABETES_ANATOMY"),
        TargetRule("renal tubules", "DIABETES_ANATOMY"),
        TargetRule("islets of Langerhans", "DIABETES_ANATOMY"),
        TargetRule("alpha cells", "DIABETES_ANATOMY"),
        TargetRule("beta cells", "DIABETES_ANATOMY"),
        TargetRule("delta cells", "DIABETES_ANATOMY"),
        TargetRule("glucagon", "DIABETES_ANATOMY"),
        TargetRule("insulin", "DIABETES_ANATOMY"),
        TargetRule("somatostatin", "DIABETES_ANATOMY"),
        TargetRule("pancreatic polypeptide", "DIABETES_ANATOMY"),
        TargetRule("vasculature", "DIABETES_ANATOMY"),
        TargetRule("neurovascular supply", "DIABETES_ANATOMY"),

        TargetRule("blood glucose monitoring", "DIABETES_PROCEDURE"),
        TargetRule("insulin injection", "DIABETES_PROCEDURE"),
        TargetRule("continuous glucose monitoring", "DIABETES_PROCEDURE"),
        TargetRule("insulin pump therapy", "DIABETES_PROCEDURE"),
        TargetRule("pancreatic islet transplantation", "DIABETES_PROCEDURE"),
        TargetRule("bariatric surgery for weight loss", "DIABETES_PROCEDURE"),
        TargetRule("oral glucose tolerance test", "DIABETES_PROCEDURE"),
        TargetRule("retinal screening", "DIABETES_PROCEDURE"),
        TargetRule("diabetic foot care", "DIABETES_PROCEDURE"),
        TargetRule("podiatry assessment", "DIABETES_PROCEDURE"),
        TargetRule("endocrinology evaluation", "DIABETES_PROCEDURE"),
        TargetRule("nutritional counseling", "DIABETES_PROCEDURE"),
        TargetRule("diabetes self-management education", "DIABETES_PROCEDURE"),

        # Diabetes Vitals
        TargetRule("blood glucose level", "DIABETES_VITAL"),
        TargetRule("hemoglobin A1c", "DIABETES_VITAL"),
        TargetRule("fasting lipid profile", "DIABETES_VITAL"),
        TargetRule("blood pressure", "DIABETES_VITAL"),
        TargetRule("body mass index", "DIABETES_VITAL"),
        TargetRule("foot examination result", "DIABETES_VITAL"),

        # Chronic Kidney Disease
        TargetRule("nephritis", "KIDNEY_DISEASE"),
        TargetRule("chronic kidney disease", "KIDNEY_DISEASE"),
        TargetRule("nephrotic syndrome", "KIDNEY_DISEASE"),
        TargetRule("renal insufficiency", "KIDNEY_DISEASE"),
        TargetRule("polycystic kidney disease", "KIDNEY_DISEASE"),
        TargetRule("renal osteodystrophy", "KIDNEY_DISEASE"),
        TargetRule("hyperkalemia", "KIDNEY_DISEASE"),
        TargetRule("acidosis", "KIDNEY_DISEASE"),
        TargetRule("uremia", "KIDNEY_DISEASE"),
        TargetRule("renal failure", "KIDNEY_DISEASE"),
        TargetRule("end-stage renal disease", "KIDNEY_DISEASE"),
        TargetRule("erythropoiesis-stimulating agent", "KIDNEY_DISEASE_MEDICATION"),
        TargetRule("iron supplement", "KIDNEY_DISEASE_MEDICATION"),
        TargetRule("phosphate binder", "KIDNEY_DISEASE_MEDICATION"),
        TargetRule("vitamin D analog", "KIDNEY_DISEASE_MEDICATION"),
        TargetRule("calcimimetic", "KIDNEY_DISEASE_MEDICATION"),
        TargetRule("loop diuretic", "KIDNEY_DISEASE_MEDICATION"),
        TargetRule("potassium binder", "KIDNEY_DISEASE_MEDICATION"),
        TargetRule("bicarbonate supplement", "KIDNEY_DISEASE_MEDICATION"),
        TargetRule("ACE inhibitor", "KIDNEY_DISEASE_MEDICATION"),
        TargetRule("angiotensin II receptor blocker", "KIDNEY_DISEASE_MEDICATION"),
        TargetRule("diabetic nephropathy", "KIDNEY_DISEASE_COMPLICATION"),
        TargetRule("chronic glomerulonephritis", "KIDNEY_DISEASE"),
        TargetRule("acute tubular necrosis", "KIDNEY_DISEASE"),
        TargetRule("kidney cyst", "KIDNEY_DISEASE"),
        TargetRule("kidney stone", "KIDNEY_DISEASE"),
        TargetRule("cystitis", "KIDNEY_DISEASE"),
        TargetRule("pyelonephritis", "KIDNEY_DISEASE"),
        TargetRule("hydronephrosis", "KIDNEY_DISEASE"),
        TargetRule("nephrectomy", "KIDNEY_DISEASE_TREATMENT"),
        TargetRule("hemodialysis", "KIDNEY_DISEASE_TREATMENT"),
        TargetRule("peritoneal dialysis", "KIDNEY_DISEASE_TREATMENT"),
        TargetRule("kidney transplantation", "KIDNEY_DISEASE_TREATMENT"),
        TargetRule("hemofiltration", "KIDNEY_DISEASE_TREATMENT"),
        TargetRule("renal angiography", "KIDNEY_DISEASE_TREATMENT"),
        TargetRule("renal biopsy", "KIDNEY_DISEASE_TREATMENT"),
        TargetRule("arteriovenous fistula", "KIDNEY_DISEASE_TREATMENT"),
        TargetRule("renal replacement therapy", "KIDNEY_DISEASE_TREATMENT"),
        TargetRule("glomerular filtration rate", "KIDNEY_FUNCTION_TEST"),
        TargetRule("creatinine clearance", "KIDNEY_FUNCTION_TEST"),
        TargetRule("urine protein test", "KIDNEY_FUNCTION_TEST"),
        TargetRule("blood urea nitrogen test", "KIDNEY_FUNCTION_TEST"),
        TargetRule("serum creatinine level", "KIDNEY_FUNCTION_TEST"),
        TargetRule("glomerular basement membrane", "KIDNEY_ANATOMY"),
        TargetRule("renal cortex", "KIDNEY_ANATOMY"),
        TargetRule("renal medulla", "KIDNEY_ANATOMY"),
        TargetRule("nephron", "KIDNEY_ANATOMY"),
        TargetRule("renal pelvis", "KIDNEY_ANATOMY"),
        TargetRule("renal artery", "KIDNEY_ANATOMY"),
        TargetRule("renal vein", "KIDNEY_ANATOMY"),
        TargetRule("ureter", "KIDNEY_ANATOMY"),
        TargetRule("interstitium", "KIDNEY_ANATOMY"),
        TargetRule("renal capsule", "KIDNEY_ANATOMY"),
        TargetRule("juxtaglomerular apparatus", "KIDNEY_ANATOMY"),
        TargetRule("podocyte", "KIDNEY_ANATOMY"),
        TargetRule("glomerulus", "KIDNEY_ANATOMY"),
        TargetRule("proximal tubule", "KIDNEY_ANATOMY"),
        TargetRule("loop of Henle", "KIDNEY_ANATOMY"),
        TargetRule("distal tubule", "KIDNEY_ANATOMY"),
        TargetRule("collecting duct", "KIDNEY_ANATOMY"),
        TargetRule("renal pelvis", "KIDNEY_ANATOMY"),
        TargetRule("renal hilum", "KIDNEY_ANATOMY"),
        TargetRule("urinary bladder", "KIDNEY_ANATOMY"),
        TargetRule("urethra", "KIDNEY_ANATOMY"),
        TargetRule("glomerular disease", "KIDNEY_DISEASE"),
        TargetRule("renal dysplasia", "KIDNEY_DISEASE"),
        TargetRule("renal infarction", "KIDNEY_DISEASE"),
        TargetRule("renal cystic disease", "KIDNEY_DISEASE"),
        TargetRule("glomerulonephritis", "KIDNEY_DISEASE"),
        TargetRule("polycystic kidney disease", "KIDNEY_DISEASE"),
        TargetRule("hydronephrosis", "KIDNEY_DISEASE"),
        TargetRule("nephrolithiasis", "KIDNEY_DISEASE"),
        TargetRule("acute kidney injury", "KIDNEY_DISEASE"),
        TargetRule("chronic kidney disease stage", "KIDNEY_DISEASE"),
        TargetRule("proteinuria", "KIDNEY_DISEASE"),
        TargetRule("hematuria", "KIDNEY_DISEASE"),
        TargetRule("hyperkalemia", "KIDNEY_DISEASE"),
        TargetRule("acidosis", "KIDNEY_DISEASE"),
        TargetRule("uremia", "KIDNEY_DISEASE"),
        TargetRule("nephritic syndrome", "KIDNEY_DISEASE"),
        TargetRule("nephrotic syndrome", "KIDNEY_DISEASE"),
        TargetRule("tubulointerstitial nephritis", "KIDNEY_DISEASE"),
        TargetRule("renal artery stenosis", "KIDNEY_DISEASE"),
        TargetRule("renal cell carcinoma", "KIDNEY_CANCER"),
        TargetRule("wilms tumor", "KIDNEY_CANCER"),
        TargetRule("transitional cell carcinoma", "KIDNEY_CANCER"),
        TargetRule("nephroblastoma", "KIDNEY_CANCER"),
        TargetRule("tuberculosis", "KIDNEY_INFECTION"),
        TargetRule("pyelonephritis", "KIDNEY_INFECTION"),
        TargetRule("cystitis", "KIDNEY_INFECTION"),
        TargetRule("glomerulonephritis", "KIDNEY_INFECTION"),
        TargetRule("schistosomiasis", "KIDNEY_INFECTION"),
        TargetRule("urinary tract infection", "KIDNEY_INFECTION"),
        TargetRule("renal failure", "KIDNEY_FAILURE"),
        TargetRule("acute renal failure", "KIDNEY_FAILURE"),
        TargetRule("chronic renal failure", "KIDNEY_FAILURE"),
        TargetRule("end-stage renal disease", "KIDNEY_FAILURE"),
        TargetRule("hemodialysis", "KIDNEY_DIALYSIS"),
        TargetRule("peritoneal dialysis", "KIDNEY_DIALYSIS"),
        TargetRule("continuous renal replacement therapy", "KIDNEY_DIALYSIS"),
        TargetRule("arteriovenous fistula", "KIDNEY_SURGERY"),
        TargetRule("percutaneous nephrolithotomy", "KIDNEY_SURGERY"),
        TargetRule("nephrectomy", "KIDNEY_SURGERY"),
        TargetRule("kidney transplant", "KIDNEY_SURGERY"),
        TargetRule("nephrolithiasis surgery", "KIDNEY_SURGERY"),
        TargetRule("cystectomy", "KIDNEY_SURGERY"),
        TargetRule("ureteral reimplantation", "KIDNEY_SURGERY"),
        TargetRule("renal biopsy", "KIDNEY_SURGERY"),
        TargetRule("pyeloplasty", "KIDNEY_SURGERY"),
            # Chronic Kidney Disease Procedures
        TargetRule("dialysis", "KIDNEY_DISEASE_PROCEDURE"),
        TargetRule("hemodialysis", "KIDNEY_DISEASE_PROCEDURE"),
        TargetRule("peritoneal dialysis", "KIDNEY_DISEASE_PROCEDURE"),
        TargetRule("kidney biopsy", "KIDNEY_DISEASE_PROCEDURE"),
        TargetRule("renal ultrasound", "KIDNEY_DISEASE_PROCEDURE"),
        TargetRule("kidney transplantation", "KIDNEY_DISEASE_PROCEDURE"),
        TargetRule("vascular access creation for hemodialysis", "KIDNEY_DISEASE_PROCEDURE"),
        TargetRule("blood pressure management", "KIDNEY_DISEASE_PROCEDURE"),
        TargetRule("anemia management", "KIDNEY_DISEASE_PROCEDURE"),

        # Chronic Kidney Disease Vitals
        TargetRule("glomerular filtration rate", "KIDNEY_DISEASE_VITAL"),
        TargetRule("serum creatinine", "KIDNEY_DISEASE_VITAL"),
        TargetRule("blood urea nitrogen", "KIDNEY_DISEASE_VITAL"),
        TargetRule("urine albumin-to-creatinine ratio", "KIDNEY_DISEASE_VITAL"),
        TargetRule("electrolyte level", "KIDNEY_DISEASE_VITAL"),
        TargetRule("parathyroid hormone level", "KIDNEY_DISEASE_VITAL"),
        TargetRule("creatinine level", "KIDNEY_DISEASE_VITAL"),

        # Chronic Kidney Disease Medications
        TargetRule("erythropoiesis-stimulating agent", "KIDNEY_DISEASE_MEDICATION"),
        TargetRule("iron supplement", "KIDNEY_DISEASE_MEDICATION"),
        TargetRule("phosphate binder", "KIDNEY_DISEASE_MEDICATION"),
        TargetRule("vitamin D analog", "KIDNEY_DISEASE_MEDICATION"),
        TargetRule("calcimimetic", "KIDNEY_DISEASE_MEDICATION"),
        TargetRule("loop diuretic", "KIDNEY_DISEASE_MEDICATION"),
        TargetRule("potassium binder", "KIDNEY_DISEASE_MEDICATION"),
        TargetRule("bicarbonate supplement", "KIDNEY_DISEASE_MEDICATION"),
        TargetRule("ACE inhibitor", "KIDNEY_DISEASE_MEDICATION"),
        TargetRule("angiotensin II receptor blocker", "KIDNEY_DISEASE_MEDICATION"),
    ]
    target_matcher.add(target_rules)
    return nlp